import swaggerAutogen from 'swagger-autogen';

const doc = {
    info: {
        version: '1.0.0',
        title: 'My API',
        description: 'Documentation automatically generated by the <b>swagger-autogen</b> module.',
    },
    host: 'localhost:7777', // todo: use env variables for ip and port
    schemes: ['http', 'https'],
};

const outputFile = 'swagger_output.json';
const endpointsFiles = ['src/routes/index.js'];

swaggerAutogen()(outputFile, endpointsFiles, doc).then(async () => {
    await import('./src/app'); // Run app
});
